title: CK Rajput
email: "chhotuchiitodiya@gmail.com"
description: Interested in AI, ML and Data Science.
about_me: My name is Chhotu. I am an experienced project lead and senior machine learning engineer with over 3 years of expertise in developing and deploying machine learning applications. Adept at project management, team leadership, and stakeholder collaboration to drive innovation and project success. Skilled in developing and implementing machine learning frameworks and libraries. I have a proven track record of delivering successful projects for clients in the Information Technology, Education and Healthcare industries. My passion lies in artificial intelligence and deep learning, where I continuously seek to expand my knowledge and skills. I thrive in problem-solving and effectively collaborate with cross-functional teams to drive project success.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chhotukumar29.github.io/CK_Rajput/" # the base hostname & protocol for your site
linked_in_link: "https://www.linkedin.com/in/chhotu-kumar-004190197/"
github_link: "https://www.github.com/chhotukumar29"
google_analytics_id: 'UA-117297510-1'
select_options: clear-filters HTML5 CSS3 SCSS javaScript jQuery materialize charts.js React jekyll Ruby-on-Rails Sinatra front-end back-end finished current
sass:
  sass_dir: assets/css/main.css
  style: compressed
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
